calc_properties_helmholtz – IAPWS
calc_properties_helmholtz Module Subroutine
23 statements
Source File
pure elemental module subroutine calc_properties_helmholtz(self, T_in, rho_in, property) Interface →
Arguments
Type Intent Optional Attributes Name
class(abst_iapws_helmholtz), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(in) :: rho_in
type(type_iapws_property), intent(inout) :: property
Calls
Called by
Source Code
    module pure elemental subroutine calc_properties_helmholtz(self, T_in, rho_in, property)
        implicit none
        class(abst_iapws_helmholtz), intent(in) :: self
        real(real64), intent(in) :: T_in
        real(real64), intent(in) :: rho_in
        type(type_iapws_property), intent(inout) :: property
        real(real64) :: tau, delta
        type(type_iapws_helmholtz_property) :: props
        property%T = T_in
        property%rho = rho_in
        tau = self%T_c / T_in
        delta = rho_in / self%rho_c
        call self%calc_phi(tau, delta, props)
        call self%calc_p(T_in, rho_in, property%p, props)
        call self%calc_u(T_in, rho_in, property%u, props)
        call self%calc_s(T_in, rho_in, property%s, props)
        call self%calc_h(T_in, rho_in, property%h, props)
        call self%calc_cp(T_in, rho_in, property%cp, props)
        call self%calc_cv(T_in, rho_in, property%cv, props)
        call self%calc_w(T_in, rho_in, property%w, props)
        call self%calc_drho_dT(T_in, rho_in, property%drho_dT, props)
        call self%calc_drho_dP(T_in, rho_in, property%drho_dP, props)
    end subroutine calc_properties_helmholtz
Call graph
calc_properties_helmholtz calls calc_phi, calc_cp_helmholtz, calc_cv_helmholtz, calc_drho_dp_helmholtz, calc_drho_dt_helmholtz, calc_h_helmholtz, calc_p_helmholtz, calc_s_helmholtz, calc_u_helmholtz, calc_w_helmholtz, calc_properties_helmholtz
calc_cp_helmholtz calls calc_cp_helmholtz, calc_phi
calc_cv_helmholtz calls calc_cv_helmholtz, calc_phi
calc_drho_dp_helmholtz calls calc_drho_dp_helmholtz, calc_phi
calc_drho_dt_helmholtz calls calc_drho_dt_helmholtz, calc_phi
calc_h_helmholtz calls calc_h_helmholtz, calc_phi
calc_p_helmholtz calls calc_p_helmholtz, calc_phi
calc_s_helmholtz calls calc_s_helmholtz, calc_phi
calc_u_helmholtz calls calc_u_helmholtz, calc_phi
calc_w_helmholtz calls calc_w_helmholtz, calc_phi