calc_properties_gibbs – IAPWS
calc_properties_gibbs Module Subroutine
23 statements
Source File
pure elemental module subroutine calc_properties_gibbs(self, T_in, P_in, property) Interface →
Arguments
Type Intent Optional Attributes Name
class(abst_iapws_gibbs), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(in) :: P_in
type(type_iapws_property), intent(inout) :: property
Calls
Called by
Source Code
    module pure elemental subroutine calc_properties_gibbs(self, T_in, P_in, property)
        implicit none
        class(abst_iapws_gibbs), intent(in) :: self
        real(real64), intent(in) :: T_in
        real(real64), intent(in) :: P_in
        type(type_iapws_property), intent(inout) :: property
        type(type_iapws_gibbs_coefficient) :: coef
        call self%calc_gamma(T_in, P_in, coef)
        call self%calc_nu(T_in, P_in, property%nu, coef)
        call self%calc_rho(T_in, P_in, property%rho, coef)
        call self%calc_drho_dT(T_in, P_in, property%drho_dT, coef)
        call self%calc_drho_dP(T_in, P_in, property%drho_dP, coef)
        call self%calc_u(T_in, P_in, property%u, coef)
        call self%calc_h(T_in, P_in, property%h, coef)
        call self%calc_s(T_in, P_in, property%s, coef)
        call self%calc_cp(T_in, P_in, property%cp, coef)
        call self%calc_cv(T_in, P_in, property%cv, coef)
        call self%calc_w(T_in, P_in, property%w, coef)
        call self%calc_alpha(T_in, P_in, property%alpha, coef)
        call self%calc_beta(T_in, P_in, property%beta, coef)
        call self%calc_kappa_T(T_in, P_in, property%kappa_T, coef)
        call self%calc_kappa_s(T_in, P_in, property%kappa_s, coef)
    end subroutine calc_properties_gibbs
Call graph
calc_properties_gibbs calls calc_gamma, calc_alpha_gibbs, calc_beta_gibbs, calc_cp_gibbs, calc_cv_gibbs, calc_drho_dp_gibbs, calc_drho_dt_gibbs, calc_h_gibbs, calc_kappa_s_gibbs, calc_kappa_t_gibbs, calc_nu_gibbs, calc_rho_gibbs, calc_s_gibbs, calc_u_gibbs, calc_w_gibbs, calc_properties_gibbs
calc_alpha_gibbs calls calc_alpha_gibbs, calc_gamma
calc_beta_gibbs calls calc_beta_gibbs, calc_gamma
calc_cp_gibbs calls calc_cp_gibbs, calc_gamma
calc_cv_gibbs calls calc_cv_gibbs, calc_gamma
calc_drho_dp_gibbs calls calc_drho_dp_gibbs, calc_gamma
calc_drho_dt_gibbs calls calc_drho_dt_gibbs, calc_gamma
calc_h_gibbs calls calc_h_gibbs, calc_gamma
calc_kappa_s_gibbs calls calc_kappa_s_gibbs, calc_gamma
calc_kappa_t_gibbs calls calc_kappa_t_gibbs, calc_gamma
calc_nu_gibbs calls calc_nu_gibbs, calc_gamma
calc_rho_gibbs calls calc_rho_gibbs, calc_gamma, calc_nu_gibbs
calc_s_gibbs calls calc_s_gibbs, calc_gamma
calc_u_gibbs calls calc_u_gibbs, calc_gamma
calc_w_gibbs calls calc_w_gibbs, calc_gamma
calc_properties_iapws97 calls calc_properties_gibbs, calc_properties_iapws97