calc_cp_iapws97 – IAPWS
calc_cp_iapws97 Module Subroutine
23 statements
Source File
pure elemental module subroutine calc_cp_iapws97(self, T_in, p_in, cp) Interface →
Calculate specific isobaric heat capacity .
Arguments
Type Intent Optional Attributes Name
class(type_iapws97), intent(in) :: self
IAPWS-97 instance
real(kind=real64), intent(in) :: T_in
Temperature [K]
real(kind=real64), intent(in) :: p_in
Pressure [Pa]
real(kind=real64), intent(inout) :: cp
Specific isobaric heat capacity [J/(kg K)]
Calls
Called by
Source Code
    module pure elemental subroutine calc_cp_iapws97(self, T_in, p_in, cp)
        implicit none
        !> IAPWS-97 instance
        class(type_iapws97), intent(in) :: self
        !> Temperature [K]
        real(real64), intent(in) :: T_in
        !> Pressure [Pa]
        real(real64), intent(in) :: p_in
        !> Specific isobaric heat capacity [J/(kg K)]
        real(real64), intent(inout) :: cp
        integer(int32) :: region_id
        real(real64) :: rho
        region_id = self%get_region(T_in, p_in)
        select case (region_id)
        case (IAPWS97_REGION_1)
            call self%region1%calc_cp(T_in, p_in, cp)
        case (IAPWS97_REGION_2)
            call self%region2%calc_cp(T_in, p_in, cp)
        case (IAPWS97_REGION_3)
            call self%region3%calc_rho(T_in, p_in, rho)
            call self%region3%calc_cp(T_in, rho, cp)
        case (IAPWS97_REGION_5)
            call self%region5%calc_cp(T_in, p_in, cp)
        case default
            error stop "IAPWS97: State out of bounds (T or P invalid) in calc_cp_iapws97."
        end select
    end subroutine calc_cp_iapws97
Call graph
calc_cp_iapws97 calls calc_cp_gibbs, calc_rho_helmholtz, get_region_iapws97, calc_cp_iapws97
calc_cp_gibbs calls calc_cp_gibbs, calc_gamma
calc_rho_helmholtz calls calc_rho_helmholtz, calc_phi, calc_p_helmholtz, calc_p_rho_helmholtz
get_region_iapws97 calls get_region_iapws97, calc_p_boundary_iapws97_region23, calc_psat_iapws97_region4
calc_p_boundary_iapws97_region23 calls calc_p_boundary_iapws97_region23
calc_p_helmholtz calls calc_p_helmholtz, calc_phi
calc_p_rho_helmholtz calls calc_p_rho_helmholtz, calc_phi
calc_psat_iapws97_region4 calls calc_psat_iapws97_region4, calc_vartheta_iapws97_region4