calc_gamma_iapws06 – IAPWS
calc_gamma_iapws06 Module Subroutine
17 statements
Source File
pure elemental module subroutine calc_gamma_iapws06(self, T_in, P_in, coef) Interface →
Calculate the Gibbs free energy properties for Ice Ih.
Arguments
Type Intent Optional Attributes Name
class(type_iapws06), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(in) :: P_in
type(type_iapws_gibbs_coefficient), intent(inout) :: coef
Calls
Called by
Source Code
    module pure elemental subroutine calc_gamma_iapws06(self, T_in, P_in, coef)
        implicit none
        class(type_iapws06), intent(in) :: self
        real(real64), intent(in) :: T_in ! [K]
        real(real64), intent(in) :: P_in ! [Pa]
        type(type_iapws_gibbs_coefficient), intent(inout) :: coef
        real(real64) :: tau, pi
        ! IAPWS-06 uses tau = T / Tt (Direct ratio, unlike IAPWS-97)
        tau = T_in / self%T_star
        ! pi = P / Pt
        pi = P_in / self%p_star
        call coef%reset()
        ! Calculate properties and store in coef
        ! These functions return Dimensional values (J/kg, m3/kg, etc.)
        coef%g = calc_gamma_iapws06_Ih(self, tau, pi)
        coef%g_p = calc_gamma_p_iapws06_Ih(self, tau, pi)
        coef%g_t = calc_gamma_t_iapws06_Ih(self, tau, pi)
        coef%g_pp = calc_gamma_pp_iapws06_Ih(self, tau, pi)
        coef%g_tt = calc_gamma_tt_iapws06_Ih(self, tau, pi)
        coef%g_pt = calc_gamma_tp_iapws06_Ih(self, tau, pi)
    end subroutine calc_gamma_iapws06
Call graph
calc_gamma_iapws06 calls calc_gamma_iapws06_ih, calc_gamma_p_iapws06_ih, calc_gamma_pp_iapws06_ih, calc_gamma_t_iapws06_ih, calc_gamma_tp_iapws06_ih, calc_gamma_tt_iapws06_ih, reset_iapws_gibbs_coefficient, calc_gamma_iapws06
calc_gamma_iapws06_ih calls calc_gamma_iapws06_ih, calc_gamma0_iapws06_ih, calc_r2_iapws06_ih
calc_gamma_p_iapws06_ih calls calc_gamma_p_iapws06_ih, calc_gamma0_p_iapws06_ih, calc_r2_p_iapws06_ih
calc_gamma_pp_iapws06_ih calls calc_gamma_pp_iapws06_ih, calc_gamma0_pp_iapws06_ih, calc_r2_pp_iapws06_ih
calc_gamma_t_iapws06_ih calls calc_gamma_t_iapws06_ih, calc_r2_iapws06_ih
calc_gamma_tp_iapws06_ih calls calc_gamma_tp_iapws06_ih, calc_r2_p_iapws06_ih
calc_gamma_tt_iapws06_ih calls calc_gamma_tt_iapws06_ih, calc_r2_iapws06_ih
reset_iapws_gibbs_coefficient calls reset_iapws_gibbs_coefficient