calc_tsat_iapws97_region4 – IAPWS
calc_tsat_iapws97_region4 Module Function
13 statements
Source File
pure elemental module function calc_tsat_iapws97_region4(self, pressure) result(T_sat) Interface →
Saturation Temperature
Arguments
Type Intent Optional Attributes Name
class(type_iapws97_region4), intent(in) :: self
real(kind=real64), intent(in) :: pressure
Return Value real(kind=real64)
Calls
Called by
Source Code
    module pure elemental function calc_tsat_iapws97_region4(self, pressure) result(T_sat)
        implicit none
        class(type_iapws97_region4), intent(in) :: self
        real(real64), intent(in) :: pressure
        real(real64) :: T_sat
        real(real64) :: beta, E, F, G, D
        ! beta = (p / p*)^0.25
        beta = calc_beta_iapws97_region4(pressure, self%p_star)
        ! Eq 31 auxiliary terms
        E = beta**2 + n_r4(3) * beta + n_r4(6)
        F = n_r4(1) * beta**2 + n_r4(4) * beta + n_r4(7)
        G = n_r4(2) * beta**2 + n_r4(5) * beta + n_r4(8)
        ! D = 2G / (-F - sqrt(F^2 - 4EG))x
        D = (2.0d0 * G) / (-F - sqrt(max((F**2 - 4.0d0 * E * G), 0.0d0)))
        ! Ts/T* = (n10 + D - sqrt((n10 + D)^2 - 4(n9 + n10*D))) / 2
        T_sat = self%T_star * (n_r4(10) + D - sqrt(max((n_r4(10) + D)**2 - 4.0d0 * (n_r4(9) + n_r4(10) * D), 0.0d0))) / 2.0d0
    end function calc_tsat_iapws97_region4
Call graph
calc_tsat_iapws97_region4 calls calc_beta_iapws97_region4, calc_tsat_iapws97_region4
calc_latent_heat_iapws97 calls calc_tsat_iapws97_region4, calc_latent_heat_iapws97