calc_drho_dT_iapws97 – IAPWS
calc_drho_dT_iapws97 Module Subroutine
19 statements
Source File
pure elemental module subroutine calc_drho_dT_iapws97(self, T_in, p_in, drho_dT) Interface →
Arguments
Type Intent Optional Attributes Name
class(type_iapws97), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(in) :: p_in
real(kind=real64), intent(inout) :: drho_dT
Calls
Called by
Source Code
    module pure elemental subroutine calc_drho_dT_iapws97(self, T_in, p_in, drho_dT)
        implicit none
        class(type_iapws97), intent(in) :: self
        real(real64), intent(in) :: T_in
        real(real64), intent(in) :: p_in
        real(real64), intent(inout) :: drho_dT
        integer(int32) :: region_id
        region_id = self%get_region(T_in, p_in)
        select case (self%get_region(T_in, p_in))
        case (IAPWS97_REGION_1)
            call self%region1%calc_drho_dT(T_in, p_in, drho_dT)
        case (IAPWS97_REGION_2)
            call self%region2%calc_drho_dT(T_in, p_in, drho_dT)
        case (IAPWS97_REGION_3)
            call self%region3%calc_drho_dT(T_in, p_in, drho_dT)
        case (IAPWS97_REGION_5)
            call self%region5%calc_drho_dT(T_in, p_in, drho_dT)
        end select
    end subroutine calc_drho_dT_iapws97
Call graph
calc_drho_dt_iapws97 calls calc_drho_dt_gibbs, get_region_iapws97, calc_drho_dt_iapws97
calc_drho_dt_gibbs calls calc_drho_dt_gibbs, calc_gamma
get_region_iapws97 calls get_region_iapws97, calc_p_boundary_iapws97_region23, calc_psat_iapws97_region4
calc_p_boundary_iapws97_region23 calls calc_p_boundary_iapws97_region23
calc_psat_iapws97_region4 calls calc_psat_iapws97_region4, calc_vartheta_iapws97_region4