calc_rho_iapws97 – IAPWS
calc_rho_iapws97 Module Subroutine
19 statements
Source File
pure elemental module subroutine calc_rho_iapws97(self, T_in, p_in, rho) Interface →
Calculate density .
Arguments
Type Intent Optional Attributes Name
class(type_iapws97), intent(in) :: self
IAPWS-97 instance
real(kind=real64), intent(in) :: T_in
Temperature [K]
real(kind=real64), intent(in) :: p_in
Pressure [Pa]
real(kind=real64), intent(inout) :: rho
Density [kg/m^3]
Calls
Called by
Source Code
    module pure elemental subroutine calc_rho_iapws97(self, T_in, p_in, rho)
        implicit none
        !> IAPWS-97 instance
        class(type_iapws97), intent(in) :: self
        !> Temperature [K]
        real(real64), intent(in) :: T_in
        !> Pressure [Pa]
        real(real64), intent(in) :: p_in
        !> Density [kg/m^3]
        real(real64), intent(inout) :: rho
        integer(int32) :: region_id
        region_id = self%get_region(T_in, p_in)
        select case (region_id)
        case (IAPWS97_REGION_1)
            call self%region1%calc_rho(T_in, p_in, rho)
        case (IAPWS97_REGION_2)
            call self%region2%calc_rho(T_in, p_in, rho)
        case (IAPWS97_REGION_3)
            call self%region3%calc_rho(T_in, p_in, rho)
        case (IAPWS97_REGION_5)
            call self%region5%calc_rho(T_in, p_in, rho)
        end select
    end subroutine calc_rho_iapws97
Call graph
calc_rho_iapws97 calls calc_rho_gibbs, get_region_iapws97, calc_rho_iapws97
calc_rho_gibbs calls calc_rho_gibbs, calc_gamma, calc_nu_gibbs
get_region_iapws97 calls get_region_iapws97, calc_p_boundary_iapws97_region23, calc_psat_iapws97_region4
calc_nu_gibbs calls calc_nu_gibbs, calc_gamma
calc_p_boundary_iapws97_region23 calls calc_p_boundary_iapws97_region23
calc_psat_iapws97_region4 calls calc_psat_iapws97_region4, calc_vartheta_iapws97_region4