calc_r2_p_iapws06_Ih – IAPWS
calc_r2_p_iapws06_Ih Function
13 statements
Source File
pure elemental function calc_r2_p_iapws06_Ih(pi, pi_0) result(val)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: pi
real(kind=real64), intent(in) :: pi_0
Return Value complex(kind=real64)
Called by
Source Code
    pure elemental function calc_r2_p_iapws06_Ih(pi, pi_0) result(val)
        implicit none
        real(real64), intent(in) :: pi, pi_0
        complex(real64) :: val
        real(real64) :: delta_pi
        integer(int32) :: i
        delta_pi = pi - pi_0
        val = r2_Ih_r2(3) * 2.0d0
        do i = 2, 2, -1
            val = r2_Ih_r2(i) * dble(i - 1) + delta_pi * val
        end do
        val = val / p_starIh
    end function calc_r2_p_iapws06_Ih
Call graph
calc_gamma_p_iapws06_ih calls calc_r2_p_iapws06_ih, calc_gamma_p_iapws06_ih
calc_gamma_tp_iapws06_ih calls calc_r2_p_iapws06_ih, calc_gamma_tp_iapws06_ih
calc_gamma_iapws06 calls calc_gamma_p_iapws06_ih, calc_gamma_tp_iapws06_ih, calc_gamma_iapws06