calc_h_helmholtz – IAPWS
calc_h_helmholtz Module Subroutine
18 statements
Source File
pure elemental module subroutine calc_h_helmholtz(self, T_in, rho_in, h, prop_in) Interface →
Arguments
Type Intent Optional Attributes Name
class(abst_iapws_helmholtz), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(in) :: rho_in
real(kind=real64), intent(inout) :: h
type(type_iapws_helmholtz_property), intent(in), optional :: prop_in
Calls
Called by
Source Code
    module pure elemental subroutine calc_h_helmholtz(self, T_in, rho_in, h, prop_in)
        implicit none
        class(abst_iapws_helmholtz), intent(in) :: self
        real(real64), intent(in) :: T_in
        real(real64), intent(in) :: rho_in
        real(real64), intent(inout) :: h
        type(type_iapws_helmholtz_property), intent(in), optional :: prop_in
        real(real64) :: tau, delta
        type(type_iapws_helmholtz_property) :: props
        tau = self%T_c / T_in
        delta = rho_in / self%rho_c
        if (present(prop_in)) then
            props = prop_in
        else
            call self%calc_phi(tau, delta, props)
        end if
        h = self%R * T_in * (tau * props%f_t + delta * props%f_d)
    end subroutine calc_h_helmholtz
Call graph
calc_h_helmholtz calls calc_phi, calc_h_helmholtz
calc_properties_helmholtz calls calc_h_helmholtz, calc_properties_helmholtz