calc_gamma_iapws97_region1 – IAPWS
calc_gamma_iapws97_region1 Module Subroutine
24 statements
Source File
pure elemental module subroutine calc_gamma_iapws97_region1(self, T_in, P_in, coef) Interface →
Calculate the Gibbs free energy for Region 1.
Arguments
Type Intent Optional Attributes Name
class(type_iapws97_region1), intent(in) :: self
IAPWS-97 Region 1 object
real(kind=real64), intent(in) :: T_in
Temperature T, [K]
real(kind=real64), intent(in) :: P_in
Pressure P, [Pa]
type(type_iapws_gibbs_coefficient), intent(inout) :: coef
IAPWS Gibbs coefficients
Calls
Called by
Source Code
    module pure elemental subroutine calc_gamma_iapws97_region1(self, T_in, P_in, coef)
        implicit none
        !> IAPWS-97 Region 1 object
        class(type_iapws97_region1), intent(in) :: self
        !> Temperature T, [K]
        real(real64), intent(in) :: T_in
        !> Pressure P, [Pa]
        real(real64), intent(in) :: P_in
        !> IAPWS Gibbs coefficients
        type(type_iapws_gibbs_coefficient), intent(inout) :: coef
        real(real64) :: tau, pi
        real(real64) :: val_g, val_gp, val_gt, val_gpp, val_gtt, val_gpt
        tau = self%T_star / T_in
        pi = P_in / self%p_star
        call coef%reset()
        ! Calculate gamma and its derivatives
        val_g = calc_gamma_region1(tau, pi)
        val_gp = calc_gamma_p_region1(tau, pi)
        val_gt = calc_gamma_t_region1(tau, pi)
        val_gpp = calc_gamma_pp_region1(tau, pi)
        val_gtt = calc_gamma_tt_region1(tau, pi)
        val_gpt = calc_gamma_pt_region1(tau, pi)
        coef%g = self%R * T_in * val_g
        coef%g_p = self%R * T_in * val_gp / self%p_star
        coef%g_t = self%R * (val_g - tau * val_gt)
        coef%g_pp = self%R * T_in * val_gpp / (self%p_star * self%p_star)
        coef%g_tt = self%R * (tau**2) * val_gtt / T_in
        coef%g_pt = self%R * (val_gp - tau * val_gpt) / self%p_star
    end subroutine calc_gamma_iapws97_region1
Call graph
calc_gamma_iapws97_region1 calls reset_iapws_gibbs_coefficient, calc_gamma_p_region1, calc_gamma_pp_region1, calc_gamma_pt_region1, calc_gamma_region1, calc_gamma_t_region1, calc_gamma_tt_region1, calc_gamma_iapws97_region1
reset_iapws_gibbs_coefficient calls reset_iapws_gibbs_coefficient
calc_gamma_p_region1 calls kahan_add
calc_gamma_pp_region1 calls kahan_add
calc_gamma_pt_region1 calls kahan_add
calc_gamma_region1 calls kahan_add
calc_gamma_t_region1 calls kahan_add
calc_gamma_tt_region1 calls kahan_add