calc_gamma_iapws97_region5 – IAPWS
calc_gamma_iapws97_region5 Module Subroutine
26 statements
Source File
pure elemental module subroutine calc_gamma_iapws97_region5(self, tau, pi, property) Interface →
Calculate the Reduced Gibbs free energy for Region 5.
Arguments
Type Intent Optional Attributes Name
class(type_iapws97_region5), intent(in) :: self
IAPWS-97 Region 5 object.
real(kind=real64), intent(in) :: tau
Inverse reduced temperature Tc/T, [-]
real(kind=real64), intent(in) :: pi
Reduced pressure p/p_c, [-]
type(type_iapws_gamma_property), intent(inout) :: property
IAPWS Gibbs properties
Calls
Called by
Source Code
    module pure elemental subroutine calc_gamma_iapws97_region5(self, tau, pi, property)
        implicit none
        !> IAPWS-97 Region 5 object.
        class(type_iapws97_region5), intent(in) :: self
        !> Inverse reduced temperature Tc/T, [-]
        real(real64), intent(in) :: tau
        !> Reduced pressure p/p_c, [-]
        real(real64), intent(in) :: pi
        !> IAPWS Gibbs properties
        type(type_iapws_gamma_property), intent(inout) :: property
        call property%reset()
        ! Calculate gamma and its derivatives
        property%gamma0 = calc_gamma0_region5(tau, pi)
        property%gamma0_p = calc_gamma0_p_region5(tau, pi)
        property%gamma0_t = calc_gamma0_t_region5(tau, pi)
        property%gamma0_pp = calc_gamma0_pp_region5(tau, pi)
        property%gamma0_tt = calc_gamma0_tt_region5(tau, pi)
        property%gamma0_pt = calc_gamma0_pt_region5(tau, pi)
        property%gammar = calc_gammar_region5(tau, pi)
        property%gammar_p = calc_gammar_p_region5(tau, pi)
        property%gammar_t = calc_gammar_t_region5(tau, pi)
        property%gammar_pp = calc_gammar_pp_region5(tau, pi)
        property%gammar_tt = calc_gammar_tt_region5(tau, pi)
        property%gammar_pt = calc_gammar_pt_region5(tau, pi)
        property%gamma = property%gamma0 + property%gammar
        property%gamma_p = property%gamma0_p + property%gammar_p
        property%gamma_t = property%gamma0_t + property%gammar_t
        property%gamma_pp = property%gamma0_pp + property%gammar_pp
        property%gamma_tt = property%gamma0_tt + property%gammar_tt
        property%gamma_pt = property%gamma0_pt + property%gammar_pt
    end subroutine calc_gamma_iapws97_region5
Call graph
calc_gamma_iapws97_region5 calls reset_iapws_gamma_property, calc_gamma0_p_region5, calc_gamma0_pp_region5, calc_gamma0_pt_region5, calc_gamma0_region5, calc_gamma0_t_region5, calc_gamma0_tt_region5, calc_gammar_p_region5, calc_gammar_pp_region5, calc_gammar_pt_region5, calc_gammar_region5, calc_gammar_t_region5, calc_gammar_tt_region5, calc_gamma_iapws97_region5
reset_iapws_gamma_property calls reset_iapws_gamma_property
calc_gamma0_region5 calls kahan_add
calc_gamma0_t_region5 calls kahan_add
calc_gamma0_tt_region5 calls kahan_add
calc_gammar_p_region5 calls kahan_add
calc_gammar_pp_region5 calls kahan_add
calc_gammar_pt_region5 calls kahan_add
calc_gammar_region5 calls kahan_add
calc_gammar_t_region5 calls kahan_add
calc_gammar_tt_region5 calls kahan_add