calc_cp_gibbs – IAPWS
calc_cp_gibbs Module Subroutine
15 statements
Source File
pure elemental module subroutine calc_cp_gibbs(self, T_in, P_in, cp, prop_in) Interface →
Arguments
Type Intent Optional Attributes Name
class(abst_iapws_gibbs), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(in) :: P_in
real(kind=real64), intent(inout) :: cp
type(type_iapws_gibbs_coefficient), intent(in), optional :: prop_in
Calls
Called by
Source Code
    module pure elemental subroutine calc_cp_gibbs(self, T_in, P_in, cp, prop_in)
        implicit none
        class(abst_iapws_gibbs), intent(in) :: self
        real(real64), intent(in) :: T_in
        real(real64), intent(in) :: P_in
        real(real64), intent(inout) :: cp
        type(type_iapws_gibbs_coefficient), intent(in), optional :: prop_in
        type(type_iapws_gibbs_coefficient) :: props
        if (present(prop_in)) then
            props = prop_in
        else
            call self%calc_gamma(T_in, P_in, props)
        end if
        cp = -T_in * props%g_tt
    end subroutine calc_cp_gibbs
Call graph
calc_cp_gibbs calls calc_gamma, calc_cp_gibbs
calc_cp_iapws97 calls calc_cp_gibbs, calc_cp_iapws97
calc_properties_gibbs calls calc_cp_gibbs, calc_properties_gibbs
calc_saturation_cp_iapws97 calls calc_cp_gibbs, calc_saturation_cp_iapws97
calc_properties_iapws97 calls calc_properties_gibbs, calc_properties_iapws97