calc_gamma_region1 – IAPWS
calc_gamma_region1 Function
13 statements
Source File
pure elemental function calc_gamma_region1(tau, pi) result(gamma)
Calculate the dimensionless Gibbs free energy for Region 1. Formula:
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: tau
Dimensionless temperature
real(kind=real64), intent(in) :: pi
Dimensionless pressure
Return Value real(kind=real64)
Resulting value
Calls
Called by
Source Code
    pure elemental function calc_gamma_region1(tau, pi) result(gamma)
        implicit none
        !> Dimensionless temperature \(\tau\)
        real(real64), intent(in) :: tau
        !> Dimensionless pressure \(\pi\)
        real(real64), intent(in) :: pi
        !> Resulting \(\gamma\) value
        real(real64) :: gamma
        integer(int32) :: i
        real(real64) :: c_gamma
        gamma = 0.0d0
        c_gamma = 0.0d0
        do i = 1, N1_terms
            call kahan_add(gamma, c_gamma, &
                           n_r1(i) * (7.1d0 - pi)**I_r1(i) * (tau - 1.222d0)**J_r1(i))
        end do
    end function calc_gamma_region1
Call graph
calc_gamma_region1 calls kahan_add
calc_gamma_iapws97_region1 calls calc_gamma_region1, calc_gamma_iapws97_region1