calc_psat_iapws97_region4 – IAPWS
calc_psat_iapws97_region4 Module Function
12 statements
Source File
pure elemental module function calc_psat_iapws97_region4(self, temperature) result(P_sat) Interface →
Saturation Pressure
Arguments
Type Intent Optional Attributes Name
class(type_iapws97_region4), intent(in) :: self
real(kind=real64), intent(in) :: temperature
Return Value real(kind=real64)
Calls
Called by
Source Code
    module pure elemental function calc_psat_iapws97_region4(self, temperature) result(P_sat)
        implicit none
        class(type_iapws97_region4), intent(in) :: self
        real(real64), intent(in) :: temperature
        real(real64) :: P_sat
        real(real64) :: vartheta, A, B, C
        vartheta = calc_vartheta_iapws97_region4(temperature, self%T_star)
        ! Eq 30 auxiliary terms
        A = vartheta**2 + n_r4(1) * vartheta + n_r4(2)
        B = n_r4(3) * vartheta**2 + n_r4(4) * vartheta + n_r4(5)
        C = n_r4(6) * vartheta**2 + n_r4(7) * vartheta + n_r4(8)
        ! Eq 30: ps/p* = [ 2C / (-B + sqrt...) ]^4
        P_sat = self%p_star * (((2.0d0 * C) / (-B + sqrt(max((B**2 - 4.0d0 * A * C), 0.0d0))))**4)
    end function calc_psat_iapws97_region4
Call graph
calc_psat_iapws97_region4 calls calc_vartheta_iapws97_region4, calc_psat_iapws97_region4
calc_latent_heat_iapws97 calls calc_psat_iapws97_region4, calc_latent_heat_iapws97
calc_saturation_cp_iapws97 calls calc_psat_iapws97_region4, calc_saturation_cp_iapws97
calc_saturation_density_iapws97 calls calc_psat_iapws97_region4, calc_saturation_density_iapws97
calc_saturation_drho_dp_iapws97 calls calc_psat_iapws97_region4, calc_saturation_drho_dp_iapws97
calc_saturation_drho_dt_iapws97 calls calc_psat_iapws97_region4, calc_saturation_drho_dt_iapws97
get_region_iapws97 calls calc_psat_iapws97_region4, get_region_iapws97
calc_cp_iapws97 calls get_region_iapws97, calc_cp_iapws97
calc_cv_iapws97 calls get_region_iapws97, calc_cv_iapws97
calc_drho_dp_iapws97 calls get_region_iapws97, calc_drho_dp_iapws97
calc_drho_dt_iapws97 calls get_region_iapws97, calc_drho_dt_iapws97
calc_h_iapws97 calls get_region_iapws97, calc_h_iapws97
calc_nu_iapws97 calls get_region_iapws97, calc_nu_iapws97
calc_properties_iapws97 calls get_region_iapws97, calc_properties_iapws97
calc_rho_iapws97 calls get_region_iapws97, calc_rho_iapws97
calc_s_iapws97 calls get_region_iapws97, calc_s_iapws97
calc_u_iapws97 calls get_region_iapws97, calc_u_iapws97
calc_w_iapws97 calls get_region_iapws97, calc_w_iapws97