calc_vartheta_iapws97_region4 – IAPWS
calc_vartheta_iapws97_region4 Function
7 statements
Source File
pure elemental function calc_vartheta_iapws97_region4(temperature, T_star) result(vartheta)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: temperature
real(kind=real64), intent(in) :: T_star
Return Value real(kind=real64)
Called by
Source Code
    pure elemental function calc_vartheta_iapws97_region4(temperature, T_star) result(vartheta)
        implicit none
        real(real64), intent(in) :: temperature
        real(real64), intent(in) :: T_star
        real(real64) :: vartheta
        ! Eq 29b: Transformed temperature vartheta
        vartheta = temperature / T_star + n_r4(9) / (temperature / T_star - n_r4(10))
    end function calc_vartheta_iapws97_region4
Call graph
calc_psat_iapws97_region4 calls calc_vartheta_iapws97_region4, calc_psat_iapws97_region4
calc_latent_heat_iapws97 calls calc_psat_iapws97_region4, calc_latent_heat_iapws97
calc_saturation_cp_iapws97 calls calc_psat_iapws97_region4, calc_saturation_cp_iapws97
calc_saturation_density_iapws97 calls calc_psat_iapws97_region4, calc_saturation_density_iapws97
get_region_iapws97 calls calc_psat_iapws97_region4, get_region_iapws97
calc_cp_iapws97 calls get_region_iapws97, calc_cp_iapws97
calc_cv_iapws97 calls get_region_iapws97, calc_cv_iapws97
calc_drho_dp_iapws97 calls get_region_iapws97, calc_drho_dp_iapws97
calc_drho_dt_iapws97 calls get_region_iapws97, calc_drho_dt_iapws97
calc_h_iapws97 calls get_region_iapws97, calc_h_iapws97
calc_nu_iapws97 calls get_region_iapws97, calc_nu_iapws97
calc_properties_iapws97 calls get_region_iapws97, calc_properties_iapws97
calc_rho_iapws97 calls get_region_iapws97, calc_rho_iapws97
calc_s_iapws97 calls get_region_iapws97, calc_s_iapws97
calc_u_iapws97 calls get_region_iapws97, calc_u_iapws97
calc_w_iapws97 calls get_region_iapws97, calc_w_iapws97