calc_properties_iapws97 – IAPWS
calc_properties_iapws97 Module Subroutine
19 statements
Source File
pure elemental module subroutine calc_properties_iapws97(self, T_in, p_in, property) Interface →
Calculate all thermodynamic properties for a given state. Dispatches calculation to the appropriate region based on and .
Arguments
Type Intent Optional Attributes Name
class(type_iapws97), intent(in) :: self
IAPWS-97 instance
real(kind=real64), intent(in) :: T_in
Temperature [K]
real(kind=real64), intent(in) :: p_in
Pressure [Pa]
type(type_iapws_property), intent(inout) :: property
Output property structure
Calls
Called by
Source Code
    module pure elemental subroutine calc_properties_iapws97(self, T_in, p_in, property)
        implicit none
        !> IAPWS-97 instance
        class(type_iapws97), intent(in) :: self
        !> Temperature [K]
        real(real64), intent(in) :: T_in
        !> Pressure [Pa]
        real(real64), intent(in) :: p_in
        !> Output property structure
        type(type_iapws_property), intent(inout) :: property
        property%region_id = self%get_region(T_in, p_in)
        select case (property%region_id)
        case (IAPWS97_REGION_1)
            call self%region1%calc_properties(T_in, p_in, property)
        case (IAPWS97_REGION_2)
            call self%region2%calc_properties(T_in, p_in, property)
        case (IAPWS97_REGION_3)
            call self%region3%calc_rho(T_in, p_in, property%rho)
            call self%region3%calc_properties(T_in, property%rho, property)
        case (IAPWS97_REGION_5)
            call self%region5%calc_properties(T_in, p_in, property)
        end select
    end subroutine calc_properties_iapws97
Call graph
calc_properties_iapws97 calls calc_properties_gibbs, calc_rho_helmholtz, get_region_iapws97, calc_properties_iapws97
calc_properties_gibbs calls calc_properties_gibbs, calc_gamma, calc_alpha_gibbs, calc_beta_gibbs, calc_cp_gibbs, calc_cv_gibbs, calc_drho_dp_gibbs, calc_drho_dt_gibbs, calc_h_gibbs, calc_kappa_s_gibbs, calc_kappa_t_gibbs, calc_nu_gibbs, calc_rho_gibbs, calc_s_gibbs, calc_u_gibbs, calc_w_gibbs
calc_rho_helmholtz calls calc_rho_helmholtz, calc_phi, calc_p_helmholtz, calc_p_rho_helmholtz
get_region_iapws97 calls get_region_iapws97, calc_p_boundary_iapws97_region23, calc_psat_iapws97_region4
calc_alpha_gibbs calls calc_alpha_gibbs, calc_gamma
calc_beta_gibbs calls calc_beta_gibbs, calc_gamma
calc_cp_gibbs calls calc_cp_gibbs, calc_gamma
calc_cv_gibbs calls calc_cv_gibbs, calc_gamma
calc_drho_dp_gibbs calls calc_drho_dp_gibbs, calc_gamma
calc_drho_dt_gibbs calls calc_drho_dt_gibbs, calc_gamma
calc_h_gibbs calls calc_h_gibbs, calc_gamma
calc_kappa_s_gibbs calls calc_kappa_s_gibbs, calc_gamma
calc_kappa_t_gibbs calls calc_kappa_t_gibbs, calc_gamma
calc_nu_gibbs calls calc_nu_gibbs, calc_gamma
calc_p_boundary_iapws97_region23 calls calc_p_boundary_iapws97_region23
calc_p_helmholtz calls calc_p_helmholtz, calc_phi
calc_p_rho_helmholtz calls calc_p_rho_helmholtz, calc_phi
calc_psat_iapws97_region4 calls calc_psat_iapws97_region4, calc_vartheta_iapws97_region4
calc_rho_gibbs calls calc_rho_gibbs, calc_gamma, calc_nu_gibbs
calc_s_gibbs calls calc_s_gibbs, calc_gamma
calc_u_gibbs calls calc_u_gibbs, calc_gamma
calc_w_gibbs calls calc_w_gibbs, calc_gamma