calc_drho_dP_gibbs – IAPWS
calc_drho_dP_gibbs Module Subroutine
15 statements
Source File
pure elemental module subroutine calc_drho_dP_gibbs(self, T_in, P_in, drho_dP, prop_in) Interface →
密度の圧力微分 (drho/dP)_T
Arguments
Type Intent Optional Attributes Name
class(abst_iapws_gibbs), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(in) :: P_in
real(kind=real64), intent(inout) :: drho_dP
type(type_iapws_gibbs_coefficient), intent(in), optional :: prop_in
Calls
Called by
Source Code
    module pure elemental subroutine calc_drho_dP_gibbs(self, T_in, P_in, drho_dP, prop_in)
        implicit none
        class(abst_iapws_gibbs), intent(in) :: self
        real(real64), intent(in) :: T_in
        real(real64), intent(in) :: P_in
        real(real64), intent(inout) :: drho_dP
        type(type_iapws_gibbs_coefficient), intent(in), optional :: prop_in
        type(type_iapws_gibbs_coefficient) :: props
        if (present(prop_in)) then
            props = prop_in
        else
            call self%calc_gamma(T_in, P_in, props)
        end if
        ! Formula: - g_pp / (g_p)^2
        drho_dP = -props%g_pp / (props%g_p**2)
    end subroutine calc_drho_dP_gibbs
Call graph
calc_drho_dp_gibbs calls calc_gamma, calc_drho_dp_gibbs
calc_drho_dp_iapws97 calls calc_drho_dp_gibbs, calc_drho_dp_iapws97
calc_properties_gibbs calls calc_drho_dp_gibbs, calc_properties_gibbs
calc_saturation_drho_dp_iapws97 calls calc_drho_dp_gibbs, calc_saturation_drho_dp_iapws97
calc_properties_iapws97 calls calc_properties_gibbs, calc_properties_iapws97