calc_phi_iapws97_region3 – IAPWS
calc_phi_iapws97_region3 Module Subroutine
14 statements
Source File
pure elemental module subroutine calc_phi_iapws97_region3(self, tau, delta, property) Interface →
Calculate the dimensionless helmholtz gibbs energy for Region 3.
Arguments
Type Intent Optional Attributes Name
class(type_iapws97_region3), intent(in) :: self
IAPWS-97 Region 3 object.
real(kind=real64), intent(in) :: tau
Inverse reduced temperature Tc/T, [-]
real(kind=real64), intent(in) :: delta
Reduced density ρ/rho_c, [-]
type(type_iapws_helmholtz_property), intent(inout) :: property
IAPWS-97 helmholtz properties
Calls
Called by
Source Code
    module pure elemental subroutine calc_phi_iapws97_region3(self, tau, delta, property)
        implicit none
        !> IAPWS-97 Region 3 object.
        class(type_iapws97_region3), intent(in) :: self
        !> Inverse reduced temperature Tc/T, [-]
        real(real64), intent(in) :: tau
        !> Reduced density ρ/rho_c, [-]
        real(real64), intent(in) :: delta
        !> IAPWS-97 helmholtz properties
        type(type_iapws_helmholtz_property), intent(inout) :: property
        call property%reset()
        ! Calculate phi and its derivatives
        property%f = calc_phi_region3(tau, delta)
        property%f_d = calc_phi_d_region3(tau, delta)
        property%f_t = calc_phi_t_region3(tau, delta)
        property%f_dd = calc_phi_dd_region3(tau, delta)
        property%f_tt = calc_phi_tt_region3(tau, delta)
        property%f_dt = calc_phi_dt_region3(tau, delta)
    end subroutine calc_phi_iapws97_region3
Call graph
calc_phi_iapws97_region3 calls reset_iapws_helmholtz_property, calc_phi_d_region3, calc_phi_dd_region3, calc_phi_dt_region3, calc_phi_region3, calc_phi_t_region3, calc_phi_tt_region3, calc_phi_iapws97_region3
reset_iapws_helmholtz_property calls reset_iapws_helmholtz_property
calc_phi_d_region3 calls kahan_add
calc_phi_dd_region3 calls kahan_add
calc_phi_dt_region3 calls kahan_add
calc_phi_region3 calls kahan_add
calc_phi_t_region3 calls kahan_add
calc_phi_tt_region3 calls kahan_add