calc_latent_heat_iapws97 – IAPWS
calc_latent_heat_iapws97 Module Subroutine
22 statements
Source File
pure elemental module subroutine calc_latent_heat_iapws97(self, latent_heat, T_in, p_in) Interface →
蒸発潜熱の計算 (Implementation)
Arguments
Type Intent Optional Attributes Name
class(type_iapws97), intent(in) :: self
real(kind=real64), intent(inout) :: latent_heat
real(kind=real64), intent(in), optional :: T_in
real(kind=real64), intent(in), optional :: p_in
Calls
Called by
Source Code
    module pure elemental subroutine calc_latent_heat_iapws97(self, latent_heat, T_in, p_in)
        implicit none
        class(type_iapws97), intent(in) :: self
        real(real64), intent(inout) :: latent_heat
        real(real64), intent(in), optional :: T_in
        real(real64), intent(in), optional :: p_in
        real(real64) :: T_sat, P_sat
        real(real64) :: h_liq, h_vap
        ! 1. 入力に基づき飽和点 (T, P) を特定
        if (present(T_in) .and. .not. present(p_in)) then
            ! 温度指定 -> 飽和圧力を計算 (Region 4)
            T_sat = T_in
            P_sat = self%region4%calc_psat(T_sat)
        else if (.not. present(T_in) .and. present(p_in)) then
            ! 圧力指定 -> 飽和温度を計算 (Region 4)
            P_sat = p_in
            T_sat = self%region4%calc_tsat(P_sat)
        else
            ! エラー: 両方指定、または両方なし
            ! 必要に応じて error stop 等を入れてください
            latent_heat = 0.0_real64
            return
        end if
        ! 2. 飽和液体エンタルピー h' (Region 1)
        ! Region 1 は abst_iapws_gibbs を継承しているため calc_h が使えます
        call self%region1%calc_h(T_sat, P_sat, h_liq)
        ! 3. 飽和蒸気エンタルピー h'' (Region 2)
        ! Region 2 も abst_iapws_gibbs を継承しているため calc_h が使えます
        call self%region2%calc_h(T_sat, P_sat, h_vap)
        ! 4. 潜熱 L = h'' - h'
        latent_heat = h_vap - h_liq
    end subroutine calc_latent_heat_iapws97
Call graph
calc_latent_heat_iapws97 calls calc_h_gibbs, calc_psat_iapws97_region4, calc_tsat_iapws97_region4, calc_latent_heat_iapws97
calc_h_gibbs calls calc_h_gibbs, calc_gamma
calc_psat_iapws97_region4 calls calc_psat_iapws97_region4, calc_vartheta_iapws97_region4
calc_tsat_iapws97_region4 calls calc_tsat_iapws97_region4, calc_beta_iapws97_region4