calc_rho_gibbs – IAPWS
calc_rho_gibbs Module Subroutine
17 statements
Source File
pure elemental module subroutine calc_rho_gibbs(self, T_in, P_in, rho, prop_in) Interface →
Arguments
Type Intent Optional Attributes Name
class(abst_iapws_gibbs), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(in) :: P_in
real(kind=real64), intent(inout) :: rho
type(type_iapws_gibbs_coefficient), intent(in), optional :: prop_in
Calls
Called by
Source Code
    module pure elemental subroutine calc_rho_gibbs(self, T_in, P_in, rho, prop_in)
        implicit none
        class(abst_iapws_gibbs), intent(in) :: self
        real(real64), intent(in) :: T_in
        real(real64), intent(in) :: P_in
        real(real64), intent(inout) :: rho
        type(type_iapws_gibbs_coefficient), intent(in), optional :: prop_in
        type(type_iapws_gibbs_coefficient) :: props
        real(real64) :: nu
        if (present(prop_in)) then
            props = prop_in
        else
            call self%calc_gamma(T_in, P_in, props)
        end if
        call self%calc_nu(T_in, P_in, nu, props)
        rho = 1.0d0 / nu
    end subroutine calc_rho_gibbs
Call graph
calc_rho_gibbs calls calc_gamma, calc_nu_gibbs, calc_rho_gibbs
calc_nu_gibbs calls calc_nu_gibbs, calc_gamma
calc_properties_gibbs calls calc_rho_gibbs, calc_properties_gibbs
calc_rho_iapws97 calls calc_rho_gibbs, calc_rho_iapws97
calc_saturation_density_iapws97 calls calc_rho_gibbs, calc_saturation_density_iapws97
calc_properties_iapws97 calls calc_properties_gibbs, calc_properties_iapws97