calc_s_iapws97 – IAPWS
calc_s_iapws97 Module Subroutine
21 statements
Source File
pure elemental module subroutine calc_s_iapws97(self, T_in, p_in, s) Interface →
Calculate specific entropy .
Arguments
Type Intent Optional Attributes Name
class(type_iapws97), intent(in) :: self
IAPWS-97 instance
real(kind=real64), intent(in) :: T_in
Temperature [K]
real(kind=real64), intent(in) :: p_in
Pressure [Pa]
real(kind=real64), intent(inout) :: s
Specific entropy [J/(kg K)]
Calls
Called by
Source Code
    module pure elemental subroutine calc_s_iapws97(self, T_in, p_in, s)
        implicit none
        !> IAPWS-97 instance
        class(type_iapws97), intent(in) :: self
        !> Temperature [K]
        real(real64), intent(in) :: T_in
        !> Pressure [Pa]
        real(real64), intent(in) :: p_in
        !> Specific entropy [J/(kg K)]
        real(real64), intent(inout) :: s
        integer(int32) :: region_id
        real(real64) :: rho
        region_id = self%get_region(T_in, p_in)
        select case (region_id)
        case (IAPWS97_REGION_1)
            call self%region1%calc_s(T_in, p_in, s)
        case (IAPWS97_REGION_2)
            call self%region2%calc_s(T_in, p_in, s)
        case (IAPWS97_REGION_3)
            call self%region3%calc_rho(T_in, p_in, rho)
            call self%region3%calc_s(T_in, rho, s)
        case (IAPWS97_REGION_5)
            call self%region5%calc_s(T_in, p_in, s)
        end select
    end subroutine calc_s_iapws97
Call graph
calc_s_iapws97 calls calc_rho_helmholtz, calc_s_gibbs, get_region_iapws97, calc_s_iapws97
calc_rho_helmholtz calls calc_rho_helmholtz, calc_phi, calc_p_helmholtz, calc_p_rho_helmholtz
calc_s_gibbs calls calc_s_gibbs, calc_gamma
get_region_iapws97 calls get_region_iapws97, calc_p_boundary_iapws97_region23, calc_psat_iapws97_region4
calc_p_boundary_iapws97_region23 calls calc_p_boundary_iapws97_region23
calc_p_helmholtz calls calc_p_helmholtz, calc_phi
calc_p_rho_helmholtz calls calc_p_rho_helmholtz, calc_phi
calc_psat_iapws97_region4 calls calc_psat_iapws97_region4, calc_vartheta_iapws97_region4