calc_gamma_iapws97_region2 – IAPWS
calc_gamma_iapws97_region2 Module Subroutine
28 statements
Source File
pure elemental module subroutine calc_gamma_iapws97_region2(self, T_in, P_in, coef) Interface →
Calculate the dimensional Gibbs free energy g and its derivatives for Region 2.
Arguments
Type Intent Optional Attributes Name
class(type_iapws97_region2), intent(in) :: self
IAPWS-97 Region 2 object.
real(kind=real64), intent(in) :: T_in
temperature T, [K]
real(kind=real64), intent(in) :: P_in
pressure P, [Pa]
type(type_iapws_gibbs_coefficient), intent(inout) :: coef
IAPWS Gibbs coefficients (Dimensional)
Calls
Called by
Source Code
    module pure elemental subroutine calc_gamma_iapws97_region2(self, T_in, P_in, coef)
        implicit none
        !> IAPWS-97 Region 2 object.
        class(type_iapws97_region2), intent(in) :: self
        !> temperature T, [K]
        real(real64), intent(in) :: T_in
        !> pressure P, [Pa]
        real(real64), intent(in) :: P_in
        !> IAPWS Gibbs coefficients (Dimensional)
        type(type_iapws_gibbs_coefficient), intent(inout) :: coef
        real(real64) :: tau, pi
        ! Local variables for dimensionless sums
        real(real64) :: val_g, val_gp, val_gt
        real(real64) :: val_gpp, val_gtt, val_gpt
        real(real64) :: RT, R_pstar
        call coef%reset()
        ! 1. Dimensionless variables (Region 2 definition)
        tau = self%T_star / T_in
        pi = P_in / self%p_star
        ! 2. Summing Ideal-gas part (0) and Residual part (r)
        !    Region 2: gamma = gamma0 + gammar
        ! gamma
        val_g = calc_gamma0_region2(tau, pi) + calc_gammar_region2(tau, pi)
        ! gamma_pi
        val_gp = calc_gamma0_p_region2(tau, pi) + calc_gammar_p_region2(tau, pi)
        ! gamma_tau
        val_gt = calc_gamma0_t_region2(tau, pi) + calc_gammar_t_region2(tau, pi)
        ! gamma_pi_pi
        val_gpp = calc_gamma0_pp_region2(tau, pi) + calc_gammar_pp_region2(tau, pi)
        ! gamma_tau_tau
        val_gtt = calc_gamma0_tt_region2(tau, pi) + calc_gammar_tt_region2(tau, pi)
        ! gamma_pi_tau
        val_gpt = calc_gamma0_pt_region2(tau, pi) + calc_gammar_pt_region2(tau, pi)
        ! 3. Convert to DIMENSIONAL quantities (The Adapter Logic)
        !    Using chain rules for tau = T*/T and pi = P/p*
        RT = self%R * T_in
        R_pstar = self%R / self%p_star ! Pre-calc R/p*
        ! g [J/kg] = R * T * gamma
        coef%g = RT * val_g
        ! g_p [m^3/kg] = (RT / p*) * gamma_pi
        coef%g_p = (RT / self%p_star) * val_gp
        ! g_t [J/(kg K)] = R * (gamma - tau * gamma_tau)  <-- Entropy term (-s)
        coef%g_t = self%R * (val_g - tau * val_gt)
        ! g_pp [m^3/(kg Pa)] = (RT / p*^2) * gamma_pi_pi
        coef%g_pp = (RT / (self%p_star**2)) * val_gpp
        ! g_tt [J/(kg K^2)] = (R * tau^2 / T) * gamma_tau_tau <-- Relates to -Cp/T
        coef%g_tt = (self%R * tau**2 / T_in) * val_gtt
        ! g_pt [m^3/(kg K)] = (R / p*) * (gamma_pi - tau * gamma_pi_tau)
        coef%g_pt = R_pstar * (val_gp - tau * val_gpt)
    end subroutine calc_gamma_iapws97_region2
Call graph
calc_gamma_iapws97_region2 calls reset_iapws_gibbs_coefficient, calc_gamma0_p_region2, calc_gamma0_pp_region2, calc_gamma0_pt_region2, calc_gamma0_region2, calc_gamma0_t_region2, calc_gamma0_tt_region2, calc_gammar_p_region2, calc_gammar_pp_region2, calc_gammar_pt_region2, calc_gammar_region2, calc_gammar_t_region2, calc_gammar_tt_region2, calc_gamma_iapws97_region2
reset_iapws_gibbs_coefficient calls reset_iapws_gibbs_coefficient
calc_gamma0_region2 calls kahan_add
calc_gamma0_t_region2 calls kahan_add
calc_gamma0_tt_region2 calls kahan_add
calc_gammar_p_region2 calls kahan_add
calc_gammar_pp_region2 calls kahan_add
calc_gammar_pt_region2 calls kahan_add
calc_gammar_region2 calls kahan_add
calc_gammar_t_region2 calls kahan_add
calc_gammar_tt_region2 calls kahan_add