calc_u_iapws97 – IAPWS
calc_u_iapws97 Module Subroutine
23 statements
Source File
pure elemental module subroutine calc_u_iapws97(self, T_in, p_in, u) Interface →
Calculate specific internal energy .
Arguments
Type Intent Optional Attributes Name
class(type_iapws97), intent(in) :: self
IAPWS-97 instance
real(kind=real64), intent(in) :: T_in
Temperature [K]
real(kind=real64), intent(in) :: p_in
Pressure [Pa]
real(kind=real64), intent(inout) :: u
Specific internal energy [J/kg]
Calls
Called by
Source Code
    module pure elemental subroutine calc_u_iapws97(self, T_in, p_in, u)
        implicit none
        !> IAPWS-97 instance
        class(type_iapws97), intent(in) :: self
        !> Temperature [K]
        real(real64), intent(in) :: T_in
        !> Pressure [Pa]
        real(real64), intent(in) :: p_in
        !> Specific internal energy [J/kg]
        real(real64), intent(inout) :: u
        integer(int32) :: region_id
        real(real64) :: rho
        region_id = self%get_region(T_in, p_in)
        select case (region_id)
        case (IAPWS97_REGION_1)
            call self%region1%calc_u(T_in, p_in, u)
        case (IAPWS97_REGION_2)
            call self%region2%calc_u(T_in, p_in, u)
        case (IAPWS97_REGION_3)
            call self%region3%calc_rho(T_in, p_in, rho)
            call self%region3%calc_u(T_in, rho, u)
        case (IAPWS97_REGION_5)
            call self%region5%calc_u(T_in, p_in, u)
        case default
            error stop "IAPWS97: State out of bounds (T or P invalid) in calc_u_iapws97."
        end select
    end subroutine calc_u_iapws97
Call graph
calc_u_iapws97 calls calc_rho_helmholtz, calc_u_gibbs, get_region_iapws97, calc_u_iapws97
calc_rho_helmholtz calls calc_rho_helmholtz, calc_phi, calc_p_helmholtz, calc_p_rho_helmholtz
calc_u_gibbs calls calc_u_gibbs, calc_gamma
get_region_iapws97 calls get_region_iapws97, calc_p_boundary_iapws97_region23, calc_psat_iapws97_region4
calc_p_boundary_iapws97_region23 calls calc_p_boundary_iapws97_region23
calc_p_helmholtz calls calc_p_helmholtz, calc_phi
calc_p_rho_helmholtz calls calc_p_rho_helmholtz, calc_phi
calc_psat_iapws97_region4 calls calc_psat_iapws97_region4, calc_vartheta_iapws97_region4