calc_cv_gibbs – IAPWS
calc_cv_gibbs Module Subroutine
18 statements
Source File
pure elemental module subroutine calc_cv_gibbs(self, T_in, p_in, cv, prop_in) Interface →
Arguments
Type Intent Optional Attributes Name
class(abst_iapws_gibbs), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(in) :: p_in
real(kind=real64), intent(inout) :: cv
type(type_iapws_gamma_property), intent(in), optional :: prop_in
Calls
Called by
Source Code
    module pure elemental subroutine calc_cv_gibbs(self, T_in, p_in, cv, prop_in)
        implicit none
        class(abst_iapws_gibbs), intent(in) :: self
        real(real64), intent(in) :: T_in
        real(real64), intent(in) :: p_in
        real(real64), intent(inout) :: cv
        type(type_iapws_gamma_property), intent(in), optional :: prop_in
        real(real64) :: tau, pi
        type(type_iapws_gamma_property) :: props
        tau = self%T_star / T_in
        pi = p_in / self%p_star
        if (present(prop_in)) then
            props = prop_in
        else
            call self%calc_gamma(tau, pi, props)
        end if
        cv = (-tau**2 * props%gamma_tt - ((props%gamma_p - tau * props%gamma_pt)**2) / props%gamma_pp) * self%R
    end subroutine calc_cv_gibbs
Call graph
calc_cv_gibbs calls calc_gamma, calc_cv_gibbs
calc_cv_iapws97 calls calc_cv_gibbs, calc_cv_iapws97
calc_properties_gibbs calls calc_cv_gibbs, calc_properties_gibbs
calc_properties_iapws97 calls calc_properties_gibbs, calc_properties_iapws97