calc_r2_iapws06_Ih – IAPWS
calc_r2_iapws06_Ih Function
12 statements
Source File
pure elemental function calc_r2_iapws06_Ih(pi, pi_0) result(val)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: pi
real(kind=real64), intent(in) :: pi_0
Return Value complex(kind=real64)
Called by
Source Code
    pure elemental function calc_r2_iapws06_Ih(pi, pi_0) result(val)
        implicit none
        real(real64), intent(in) :: pi, pi_0
        complex(real64) :: val
        real(real64) :: delta_pi
        integer(int32) :: i
        delta_pi = pi - pi_0
        val = r2_Ih_r2(r2_terms)
        do i = r2_terms - 1, 1, -1
            val = r2_Ih_r2(i) + delta_pi * val
        end do
    end function calc_r2_iapws06_Ih
Call graph
calc_gamma_iapws06_ih calls calc_r2_iapws06_ih, calc_gamma_iapws06_ih
calc_gamma_t_iapws06_ih calls calc_r2_iapws06_ih, calc_gamma_t_iapws06_ih
calc_gamma_tt_iapws06_ih calls calc_r2_iapws06_ih, calc_gamma_tt_iapws06_ih
calc_gamma_iapws06 calls calc_gamma_iapws06_ih, calc_gamma_t_iapws06_ih, calc_gamma_tt_iapws06_ih, calc_gamma_iapws06