calc_p_rho_helmholtz – IAPWS
calc_p_rho_helmholtz Module Subroutine
21 statements
Source File
pure elemental module subroutine calc_p_rho_helmholtz(self, T_in, rho_in, p_rho, prop_in) Interface →
Arguments
Type Intent Optional Attributes Name
class(abst_iapws_helmholtz), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(in) :: rho_in
real(kind=real64), intent(inout) :: p_rho
type(type_iapws_helmholtz_property), intent(in), optional :: prop_in
Calls
Called by
Source Code
    module pure elemental subroutine calc_p_rho_helmholtz(self, T_in, rho_in, p_rho, prop_in)
        implicit none
        class(abst_iapws_helmholtz), intent(in) :: self
        real(real64), intent(in) :: T_in
        real(real64), intent(in) :: rho_in
        real(real64), intent(inout) :: p_rho
        type(type_iapws_helmholtz_property), intent(in), optional :: prop_in
        real(real64) :: tau, delta
        type(type_iapws_helmholtz_property) :: props
        real(real64) :: R, RT
        tau = self%T_c / T_in
        delta = rho_in / self%rho_c
        R = self%R
        RT = R * T_in
        ! φ, φ_d, φ_dd の取得
        if (present(prop_in)) then
            props = prop_in
        else
            call self%calc_phi(tau, delta, props)
        end if
        ! p_rho = R * T_in * (delta * props%f_d + delta * props%f_d + delta**2 * props%f_dd) / self%rho_c
        p_rho = R * T_in * (2.0d0 * delta * props%f_d + delta**2 * props%f_dd)
    end subroutine calc_p_rho_helmholtz
Call graph
calc_p_rho_helmholtz calls calc_phi, calc_p_rho_helmholtz
calc_rho_helmholtz calls calc_p_rho_helmholtz, calc_rho_helmholtz
calc_cp_iapws97 calls calc_rho_helmholtz, calc_cp_iapws97
calc_cv_iapws97 calls calc_rho_helmholtz, calc_cv_iapws97
calc_h_iapws97 calls calc_rho_helmholtz, calc_h_iapws97
calc_nu_iapws97 calls calc_rho_helmholtz, calc_nu_iapws97
calc_properties_iapws97 calls calc_rho_helmholtz, calc_properties_iapws97
calc_s_iapws97 calls calc_rho_helmholtz, calc_s_iapws97
calc_u_iapws97 calls calc_rho_helmholtz, calc_u_iapws97
calc_w_iapws97 calls calc_rho_helmholtz, calc_w_iapws97