kahan_add – IAPWS
kahan_add Subroutine
11 statements
Source File
public pure elemental subroutine kahan_add(sum, c, input)
Helper subroutine for Kahan Summation Algorithm (Compensated Summation) Reduces numerical error when adding a sequence of finite precision floating point numbers.
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(inout) :: sum
real(kind=real64), intent(inout) :: c
real(kind=real64), intent(in) :: input
Called by
Source Code
    pure elemental subroutine kahan_add(sum, c, input)
        implicit none
        real(real64), intent(inout) :: sum ! Current sum
        real(real64), intent(inout) :: c ! Compensation (carry) variable
        real(real64), intent(in) :: input ! Value to add
        real(real64) :: y, t
        y = input - c ! So far, so good: c is zero.
        t = sum + y ! Alas, sum is big, y small, so low-order digits of y are lost.
        c = (t - sum) - y ! (t - sum) recovers the high-order part of y; subtracting y recovers -(low part of y)
        sum = t ! Algebraically, c should always be zero. Beware overly-aggressive optimizing compilers!
    end subroutine kahan_add
Call graph
calc_gamma0_region2 calls kahan_add
calc_gamma0_region5 calls kahan_add
calc_gamma0_t_region2 calls kahan_add
calc_gamma0_t_region5 calls kahan_add
calc_gamma0_tt_region2 calls kahan_add
calc_gamma0_tt_region5 calls kahan_add
calc_gamma_p_region1 calls kahan_add
calc_gamma_pp_region1 calls kahan_add
calc_gamma_pt_region1 calls kahan_add
calc_gamma_region1 calls kahan_add
calc_gamma_t_region1 calls kahan_add
calc_gamma_tt_region1 calls kahan_add
calc_gammar_p_region2 calls kahan_add
calc_gammar_p_region5 calls kahan_add
calc_gammar_pp_region2 calls kahan_add
calc_gammar_pp_region5 calls kahan_add
calc_gammar_pt_region2 calls kahan_add
calc_gammar_pt_region5 calls kahan_add
calc_gammar_region2 calls kahan_add
calc_gammar_region5 calls kahan_add
calc_gammar_t_region2 calls kahan_add
calc_gammar_t_region5 calls kahan_add
calc_gammar_tt_region2 calls kahan_add
calc_gammar_tt_region5 calls kahan_add
calc_phi0_iapws95 calls kahan_add, calc_phi0_iapws95
calc_phi_d_region3 calls kahan_add
calc_phi_dd_region3 calls kahan_add
calc_phi_dt_region3 calls kahan_add
calc_phi_region3 calls kahan_add
calc_phi_t_region3 calls kahan_add
calc_phi_tt_region3 calls kahan_add
calc_phir_iapws95 calls kahan_add, calc_phir_iapws95
calc_gamma_iapws97_region1 calls calc_gamma_p_region1, calc_gamma_pp_region1, calc_gamma_pt_region1, calc_gamma_region1, calc_gamma_t_region1, calc_gamma_tt_region1, calc_gamma_iapws97_region1
calc_gamma_iapws97_region2 calls calc_gamma0_region2, calc_gamma0_t_region2, calc_gamma0_tt_region2, calc_gammar_p_region2, calc_gammar_pp_region2, calc_gammar_pt_region2, calc_gammar_region2, calc_gammar_t_region2, calc_gammar_tt_region2, calc_gamma_iapws97_region2
calc_gamma_iapws97_region5 calls calc_gamma0_region5, calc_gamma0_t_region5, calc_gamma0_tt_region5, calc_gammar_p_region5, calc_gammar_pp_region5, calc_gammar_pt_region5, calc_gammar_region5, calc_gammar_t_region5, calc_gammar_tt_region5, calc_gamma_iapws97_region5
calc_phi_iapws97_region3 calls calc_phi_d_region3, calc_phi_dd_region3, calc_phi_dt_region3, calc_phi_region3, calc_phi_t_region3, calc_phi_tt_region3, calc_phi_iapws97_region3
calc_phi_iapws95 calls calc_phi0_iapws95, calc_phir_iapws95, calc_phi_iapws95