reset_iapws_helmholtz_property – IAPWS
reset_iapws_helmholtz_property Module Subroutine
22 statements
Source File
pure elemental module subroutine reset_iapws_helmholtz_property(self) Interface →
Arguments
Type Intent Optional Attributes Name
class(type_iapws_helmholtz_property), intent(inout) :: self
IAPWS Helmholtz properties object
Called by
Source Code
    module pure elemental subroutine reset_iapws_helmholtz_property(self)
        implicit none
        !> IAPWS Helmholtz properties object
        class(type_iapws_helmholtz_property), intent(inout) :: self
        self%f = 0.0d0
        self%f_d = 0.0d0
        self%f_t = 0.0d0
        self%f_dd = 0.0d0
        self%f_dt = 0.0d0
        self%f_tt = 0.0d0
        self%f0 = 0.0d0
        self%f0_d = 0.0d0
        self%f0_t = 0.0d0
        self%f0_dd = 0.0d0
        self%f0_dt = 0.0d0
        self%f0_tt = 0.0d0
        self%fr = 0.0d0
        self%fr_d = 0.0d0
        self%fr_t = 0.0d0
        self%fr_dd = 0.0d0
        self%fr_dt = 0.0d0
        self%fr_tt = 0.0d0
    end subroutine reset_iapws_helmholtz_property
Call graph
reset_iapws_helmholtz_property calls reset_iapws_helmholtz_property
calc_phi_iapws97_region3 calls reset_iapws_helmholtz_property, calc_phi_iapws97_region3