calc_saturation_drho_dT_iapws97 – IAPWS
calc_saturation_drho_dT_iapws97 Interface
125 statements
Source File
interface
Calls
private pure elemental module subroutine calc_saturation_drho_dT_iapws97(self, T_in, drho_dT_vap, drho_dT_liq) Implementation →
Arguments
Type Intent Optional Attributes Name
class(type_iapws97), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(inout), optional :: drho_dT_vap
飽和蒸気 (Region 2) の (d_rho/d_T)_P
real(kind=real64), intent(inout), optional :: drho_dT_liq
飽和液体 (Region 1) の (d_rho/d_T)_P
Call graph
calc_saturation_drho_dt_iapws97 calls calc_saturation_drho_dt_iapws97, calc_drho_dt_gibbs, calc_psat_iapws97_region4
calc_drho_dt_gibbs calls calc_drho_dt_gibbs, calc_gamma
calc_psat_iapws97_region4 calls calc_psat_iapws97_region4, calc_vartheta_iapws97_region4