calc_drho_dT_gibbs – IAPWS
calc_drho_dT_gibbs Interface
121 statements
Source File
interface
Calls
Called by
private pure elemental module subroutine calc_drho_dT_gibbs(self, T_in, P_in, drho_dT, prop_in) Implementation →
Arguments
Type Intent Optional Attributes Name
class(abst_iapws_gibbs), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(in) :: P_in
real(kind=real64), intent(inout) :: drho_dT
type(type_iapws_gibbs_coefficient), intent(in), optional :: prop_in
Description
密度の温度微分 (drho/dT)_P
Call graph
calc_drho_dt_gibbs calls calc_drho_dt_gibbs, calc_gamma
calc_drho_dt_iapws97 calls calc_drho_dt_gibbs, calc_drho_dt_iapws97
calc_properties_gibbs calls calc_drho_dt_gibbs, calc_properties_gibbs
calc_saturation_drho_dt_iapws97 calls calc_drho_dt_gibbs, calc_saturation_drho_dt_iapws97
calc_properties_iapws97 calls calc_properties_gibbs, calc_properties_iapws97