calc_saturation_density_iapws97 – IAPWS
calc_saturation_density_iapws97 Interface
104 statements
Source File
interface
Calls
private pure elemental module subroutine calc_saturation_density_iapws97(self, T_in, rho_vap, rho_liq) Implementation →
Arguments
Type Intent Optional Attributes Name
class(type_iapws97), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(inout), optional :: rho_vap
real(kind=real64), intent(inout), optional :: rho_liq
Description
飽和蒸気密度と飽和液体密度を計算 (T入力)
Call graph
calc_saturation_density_iapws97 calls calc_saturation_density_iapws97, calc_psat_iapws97_region4, calc_rho_gibbs
calc_psat_iapws97_region4 calls calc_psat_iapws97_region4, calc_vartheta_iapws97_region4
calc_rho_gibbs calls calc_rho_gibbs, calc_gamma, calc_nu_gibbs
calc_nu_gibbs calls calc_nu_gibbs, calc_gamma