calc_phi_iapws95 – IAPWS
calc_phi_iapws95 Interface
27 statements
Source File
interface
Calls
private pure elemental module subroutine calc_phi_iapws95(self, tau, delta, property) Implementation →
Arguments
Type Intent Optional Attributes Name
class(type_iapws95), intent(in) :: self
IAPWS-95 model instance
real(kind=real64), intent(in) :: tau
Inverse reduced temperature Tc/T, [-]
real(kind=real64), intent(in) :: delta
Reduced density ρ/rho_c, [-]
type(type_iapws_phi_property), intent(inout) :: property
IAPWS-95 helmholtz properties
Call graph
calc_phi_iapws95 calls calc_phi_iapws95, calc_phi0_iapws95, calc_phir_iapws95
calc_phi0_iapws95 calls calc_phi0_iapws95, kahan_add
calc_phir_iapws95 calls calc_phir_iapws95, kahan_add