calc_saturation_drho_dP_iapws97 – IAPWS
calc_saturation_drho_dP_iapws97 Interface
125 statements
Source File
interface
Calls
private pure elemental module subroutine calc_saturation_drho_dP_iapws97(self, T_in, drho_dP_vap, drho_dP_liq) Implementation →
Arguments
Type Intent Optional Attributes Name
class(type_iapws97), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(inout), optional :: drho_dP_vap
飽和蒸気 (Region 2) の (d_rho/d_P)_T
real(kind=real64), intent(inout), optional :: drho_dP_liq
飽和液体 (Region 1) の (d_rho/d_P)_T
Call graph
calc_saturation_drho_dp_iapws97 calls calc_saturation_drho_dp_iapws97, calc_drho_dp_gibbs, calc_psat_iapws97_region4
calc_drho_dp_gibbs calls calc_drho_dp_gibbs, calc_gamma
calc_psat_iapws97_region4 calls calc_psat_iapws97_region4, calc_vartheta_iapws97_region4