calc_w_gibbs – IAPWS
calc_w_gibbs Interface
121 statements
Source File
interface
Calls
Called by
public pure elemental module subroutine calc_w_gibbs(self, T_in, p_in, w, prop_in) Implementation →
Arguments
Type Intent Optional Attributes Name
class(abst_iapws_gibbs), intent(in) :: self
IAPWS Gibbs model instance
real(kind=real64), intent(in) :: T_in
Temperature, T [K].
real(kind=real64), intent(in) :: p_in
Pressure, P [Pa].
real(kind=real64), intent(inout) :: w
Speed of sound, w [m/s].
type(type_iapws_gibbs_coefficient), intent(in), optional :: prop_in
Gibbs coefficients
Description
Calculate speed of sound using Gibbs formulation
Call graph
calc_w_gibbs calls calc_w_gibbs, calc_gamma
calc_properties_gibbs calls calc_w_gibbs, calc_properties_gibbs
calc_w_iapws97 calls calc_w_gibbs, calc_w_iapws97
calc_properties_iapws97 calls calc_properties_gibbs, calc_properties_iapws97