calc_u_gibbs – IAPWS
calc_u_gibbs Interface
73 statements
Source File
interface
Calls
Called by
public pure elemental module subroutine calc_u_gibbs(self, T_in, p_in, u, prop_in) Implementation →
Arguments
Type Intent Optional Attributes Name
class(abst_iapws_gibbs), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(in) :: p_in
real(kind=real64), intent(inout) :: u
type(type_iapws_gamma_property), intent(in), optional :: prop_in
Call graph
calc_u_gibbs calls calc_u_gibbs, calc_gamma
calc_properties_gibbs calls calc_u_gibbs, calc_properties_gibbs
calc_u_iapws97 calls calc_u_gibbs, calc_u_iapws97
calc_properties_iapws97 calls calc_properties_gibbs, calc_properties_iapws97