get_region_iapws97 – IAPWS
get_region_iapws97 Interface
76 statements
Source File
interface
Calls
Called by
public pure elemental module function get_region_iapws97(self, T_in, p_in) result(region_id) Implementation →
Arguments
Type Intent Optional Attributes Name
class(type_iapws97), intent(in) :: self
real(kind=real64), intent(in) :: T_in
real(kind=real64), intent(in) :: p_in
Return Value integer(kind=int32)
Call graph
get_region_iapws97 calls get_region_iapws97, calc_p_boundary_iapws97_region23, calc_psat_iapws97_region4
calc_p_boundary_iapws97_region23 calls calc_p_boundary_iapws97_region23
calc_psat_iapws97_region4 calls calc_psat_iapws97_region4, calc_vartheta_iapws97_region4
calc_cp_iapws97 calls get_region_iapws97, calc_cp_iapws97
calc_cv_iapws97 calls get_region_iapws97, calc_cv_iapws97
calc_h_iapws97 calls get_region_iapws97, calc_h_iapws97
calc_nu_iapws97 calls get_region_iapws97, calc_nu_iapws97
calc_properties_iapws97 calls get_region_iapws97, calc_properties_iapws97
calc_rho_iapws97 calls get_region_iapws97, calc_rho_iapws97
calc_s_iapws97 calls get_region_iapws97, calc_s_iapws97
calc_u_iapws97 calls get_region_iapws97, calc_u_iapws97
calc_w_iapws97 calls get_region_iapws97, calc_w_iapws97