#!/bin/bash

# Display help function
usage() {
    echo "Usage: $0 [compiler|clean] [build_type]"
    echo ""
    echo "Commands:"
    echo "  clean    Clean build artifacts (fpm clean + bin/lib removal)"
    echo ""
    echo "Compilers:"
    echo "  gcc      (gfortran)"
    echo "  intel    (ifx)"
    echo "  nvidia   (nvfortran)"
    echo ""
    echo "Build Types:"
    echo "  debug"
    echo "  release"
    echo ""
    echo "Example:"
    echo "  $0 gcc debug"
    echo "  $0 clean"
    exit 1
}

# Cleanup process
if [ "$1" == "clean" ]; then
    echo "Cleaning build artifacts..."
    set -x
    # Remove fpm build directory (includes cache with --all)
    fpm clean --all
    # Remove bin and lib directories potentially generated by CMake
    rm -rf bin lib
    set +x
    echo "Done."
    exit 0
fi

# Show help if arguments are missing
if [ $# -lt 2 ]; then
    usage
fi

COMPILER_INPUT=$1
BUILD_TYPE_INPUT=$2

# Convert input to lowercase
COMPILER=$(echo "$COMPILER_INPUT" | tr '[:upper:]' '[:lower:]')
BUILD_TYPE=$(echo "$BUILD_TYPE_INPUT" | tr '[:upper:]' '[:lower:]')

# Initialize variables
FC=""
FLAGS=""

# Set flags according to compiler and build type
# Corresponds to cacheVariables in CMakePresets.json
case "$COMPILER" in
    gcc)
        FC="gfortran"
        # base: -Wall -Wextra -fopenmp
        BASE_FLAGS="-Wall -Wextra -fopenmp"
        
        if [ "$BUILD_TYPE" == "debug" ]; then
            # gcc-debug
            FLAGS="$BASE_FLAGS -g -O0 -fcheck=all -fbacktrace"
        elif [ "$BUILD_TYPE" == "release" ]; then
            # gcc-release
            FLAGS="$BASE_FLAGS -O3 -march=native -ffast-math"
        else
            echo "Error: Unknown build type '$BUILD_TYPE'"
            usage
        fi
        ;;

    intel)
        FC="ifx"
        # base: -fpp -traceback -warn all -qopenmp
        BASE_FLAGS="-fpp -traceback -warn all -qopenmp"

        if [ "$BUILD_TYPE" == "debug" ]; then
            # intel-debug
            FLAGS="$BASE_FLAGS -g -O0 -check all -fpe0"
        elif [ "$BUILD_TYPE" == "release" ]; then
            # intel-release
            FLAGS="$BASE_FLAGS -O3 -xHost"
        else
            echo "Error: Unknown build type '$BUILD_TYPE'"
            usage
        fi
        ;;

    nvidia)
        FC="nvfortran"
        # base: -Minfo=all -mp
        BASE_FLAGS="-Minfo=all -mp"

        if [ "$BUILD_TYPE" == "debug" ]; then
            # nvidia-debug
            FLAGS="$BASE_FLAGS -g -O0 -Mbounds -Mchkptr -traceback -Ktrap=fp"
        elif [ "$BUILD_TYPE" == "release" ]; then
            # nvidia-release
            FLAGS="$BASE_FLAGS -O3 -fast"
        else
            echo "Error: Unknown build type '$BUILD_TYPE'"
            usage
        fi
        ;;

    *)
        echo "Error: Unknown compiler '$COMPILER'"
        usage
        ;;
esac

# Display configuration
echo "========================================================="
echo " FPM Build Configuration"
echo "========================================================="
echo " Compiler   : $FC"
echo " Build Type : $BUILD_TYPE"
echo " Flags      : $FLAGS"
echo "========================================================="


# Execute build
# Run in order: Build -> Test, similar to CMake workflow
fpm build --compiler "$FC" --flag "$FLAGS"
BUILD_STATUS=$?

if [ $BUILD_STATUS -eq 0 ]; then
    echo "Build successful. Running tests..."
    fpm test --compiler "$FC" --flag "$FLAGS"
else
    echo "Build failed."
    exit $BUILD_STATUS
fi